apiVersion: v2
name: n8n
version: 1.0.0
appVersion: 1.85.1
type: application
description: "Helm Chart for deploying n8n on Google Kubernetes Engine, a fair-code workflow automation platform with native AI capabilities for technical teams. Easily automate tasks across different services."
home: https://github.com/PhiloSoftware/n8n-gcp-helm
keywords:
  - Workflow Automation
  - Workflow
  - iPaaS
  - integration-framework
  - low-code-plattform
  - low-code
sources:
  - https://github.com/n8n-io/n8n
  - https://n8n.io/
maintainers:
  - name: Philo Software
    email: contact@philo.co.nz
    url: https://github.com/PhiloSoftware