postgres:
  host: 127.0.0.1
  port: "5432"
  database: notset
  user: user
  password: password
ingress:
  host: yoururl.com
  traefik:
    apiVersion: traefik.containo.us/v1alpha1
cloudsql:
  credentialsjsonb64: undefined
  connectionString: undefined
