apiVersion: {{ .Values.ingress.traefik.apiVersion }}
kind: IngressRoute
metadata:
  name: n8n-ingressroute
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      services:
        - name: n8n
          port: 5678
      middlewares:
        - name: n8n-securityheaders
        - name: n8n-redirectscheme