apiVersion: {{ .Values.ingress.traefik.apiVersion }}
kind: Middleware
metadata:
  name: n8n-redirectscheme
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: n8n-securityheaders
spec:
  headers:
    customResponseHeaders:
      server: ""
      X-Frame-Options: "SAMEORIGIN"
      X-XSS-Protection: "1; mode=block"
      X-Content-Type-Options: "nosniff"
      Strict-Transport-Security: "max-age=31536000; includeSubDomains;"