apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.user }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password }}
  POSTGRES_DB: {{ .Values.postgres.database }}
  POSTGRES_NON_ROOT_USER: {{ .Values.postgres.user }}
  POSTGRES_NON_ROOT_PASSWORD: {{ .Values.postgres.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cloud-sql-secret
type: Opaque
data:
  credentials.json: {{ .Values.cloudsql.credentialsjsonb64 }}